# Generated by Django 4.0.5 on 2022-07-02 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuser',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 1, 55, 51, 43397)),
        ),
    ]
