# Generated by Django 4.0.5 on 2022-07-02 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_alter_inventoryuser_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuser',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 2, 0, 51, 906865)),
        ),
    ]
